#!/usr/bin/env bash
sed -i "s/Listen 80/Listen ${PORT:-80}/g" /etc/apache2/ports.conf
sed -i "s/:80/:${PORT:-80}/g" /etc/apache2/sites-enabled/*
echo "ServerName 127.0.0.1" >> /etc/apache2/apache2.conf
apache2-foreground

